#!/usr/bin/env python3

import os
import datetime
import random
import pytz

import libtaxii as t
import libtaxii.clients as tc
import libtaxii.messages_11 as tm11
from libtaxii.common import gen_filename
from libtaxii.constants import *

from configobj import ConfigObj
from FSISAC_STIX_Parser import *
from glob import glob


config = ConfigObj("fsisac.conf")

FSISAC_USERNAME = config["FSISAC_USERNAME"]
FSISAC_PASSWORD = config["FSISAC_PASSWORD"]
FSISAC_KEY = config["FSISAC_KEY"]
FSISAC_CERT = config["FSISAC_CERT"]

STIX_DOWNLOADED_PATH = config["FSISAC_STIX_DOWNLOADED_PATH"]
FSISAC_JSON_OUTPUT_PATH = config["FSISAC_JSON_OUTPUT_PATH"]
DOWNLOAD_INTERVAL_MINUTE = int(config.get("DOWNLOAD_INTERVAL_MINUTE", 60))

class FSISAC_STIX_Downloader:
    def __init__(self):
        os.makedirs(STIX_DOWNLOADED_PATH, exist_ok=True)

    def process_fsisac_stix_for_today(self):
        today = datetime.datetime.now(tz=pytz.UTC)

        client = tc.HttpClient()
        client.set_auth_type(tc.HttpClient.AUTH_CERT_BASIC)
        client.set_use_https(True)

        client.auth_credentials["username"] = FSISAC_USERNAME
        client.auth_credentials["password"] = FSISAC_PASSWORD
        client.auth_credentials["key_file"] = FSISAC_KEY
        client.auth_credentials["cert_file"] = FSISAC_CERT

        taxii_server = "analysis.fsisac.com"
        taxii_service = "/taxii-discovery-service/"
        feed = "system.Default"

        start = today - datetime.timedelta(days=1)
        end = today

        inc_start = start
        inc_end = inc_start + datetime.timedelta(days=1)

        while inc_start <= end:
            params = tm11.PollParameters()

            poll_request = tm11.PollRequest(
                tm11.generate_message_id(),
                collection_name=feed,
                poll_parameters=params,
                exclusive_begin_timestamp_label=inc_start,
                inclusive_end_timestamp_label=inc_end
            )

            poll_xml = poll_request.to_xml()

            http_resp = client.call_taxii_service2(
                taxii_server,
                taxii_service,
                VID_TAXII_XML_11,
                poll_xml
            )

            taxii_message = t.get_message_from_http_response(
                http_resp,
                poll_request.message_id
            )

            for cb in taxii_message.content_blocks:
                filename = gen_filename(
                    "FSISAC",
                    "_STIX111_",
                    cb.timestamp_label.isoformat(),
                    ".xml"
                )

                filepath = os.path.join(STIX_DOWNLOADED_PATH, filename)

                with open(filepath, "wb") as outfile:
                    outfile.write(cb.content)

            inc_start += datetime.timedelta(days=1)
            inc_end += datetime.timedelta(days=1)

    def process_stix_directory(self):
        done_dir = os.path.join(STIX_DOWNLOADED_PATH, "done")
        os.makedirs(done_dir, exist_ok=True)

        stix_files = glob(os.path.join(STIX_DOWNLOADED_PATH, "*.xml"))

        for one_file in stix_files:
            filename_only = os.path.basename(one_file)

            stixParser = FSISAC_STIX_Parser()
            result_json = stixParser.parse_stix_file(one_file)

            out_file = os.path.join(
                FSISAC_JSON_OUTPUT_PATH,
                f"json_{filename_only.replace('.', '_')}_{random.randint(10**15, 10**16-1)}.json"
            )

            with open(out_file, "w", encoding="utf-8") as f:
                f.write(result_json)

            os.rename(one_file, os.path.join(done_dir, filename_only))


if __name__ == "__main__":
    print_banner()
    downloader = FSISAC_STIX_Downloader()
    downloader.process_fsisac_stix_for_today()
    downloader.process_stix_directory()
    print("[Done!]")
